### PR TITLE
Code ETHWallpaper v2. #14

### PR DESCRIPTION
**Pull request by stojce**
Issue https://github.com/gitcoinco/skunkworks/issues/14

### CODE REVIEW

**Comment by owocki** [comment]
neat, looking forward to playing with it :)

i dont feel the need to code review line by line.  lmk if you want to deploy this already

**Comment by stojce** [comment]
@owocki  Deployed to live server. You can play around ;)

**Comment by owocki** [comment]
@stojce i just uploaded a bunch of new wallpapers and get this message now 

http://bits.owocki.com/3L3i0b3m0Z3d/Screen%20Shot%202017-12-31%20at%2011.10.19%20AM.png

but i dont seem to ever get the email when they are processed..

**Comment by owocki** [comment]
is there some queue that needs enabled?  do we need to put the live sendgrid key on the server?

**Comment by owocki** [comment]
http://bits.owocki.com/343O1w1Q041M/Screen%20Shot%202017-12-31%20at%2011.21.01%20AM.png


looks like they finally processed, but... 

1. from email address is misspelled.  you can just make it come from founders@gitcoin.co
2. image on the page doesnt work :( https://ethwallpaper.co/preview/99313fe3-4acf-4e55-90fa-71719217c4c7

**Comment by owocki** [comment]
ahh the link doesnt work because its https and https doesnt work

**Comment by stojce** [comment]
Ok, i'll change the sender info. The queue is set to run every 5 minutes, so it might take 5 or more minutes for wallpapers to be processed. This can be easily changed to more frequent period. 
SSL is set  - in fact, somone else already set the SSL and works. I've checked the link and works for me, please tell me what doesn't work - are you getting empty page?

**Comment by owocki** [comment]
screenshots: http://bits.owocki.com/2J2A1R1j0q2i/Screen%20Shot%202017-12-31%20at%2012.00.13%20PM.png
http://bits.owocki.com/2h2T1Q183O3a/Screen%20Shot%202017-12-31%20at%2012.00.43%20PM.png

no im not getting an empty page on https, but it does seem that none of the wallpapers are being served

**Comment by stojce** [comment]
I can see your wallpapers. This might be a cache issue - please try to clear the cache or try different browser to check if that works/
screenshot from 2017-12-31 20-05-47
screenshot from 2017-12-31 20-04-44

**Comment by owocki** [comment]
ah ur right.  it is a cache issue.  my bad

should we turn off http traffic so only https traffic can go through?  donno if thats hard or not. happy to send a tip if so since it wasnt in original scope

**Comment by stojce** [comment]
np. i'll set it up tomorrow.

**Comment by owocki** [comment]
@stojce ill payout the bounty now. thanks again.

**Pull request merged**
